### PR TITLE
Add phone auth template

### PR DESCRIPTION
**Pull request by ethanblake4**
This posts a request to /auth with the phone number you enter, but currently doesn't use the result since our account creation screen is not finished.

Also reverts a few changes from https://github.com/PullDating/FlutterApplication/commit/b64531ee2330f60cef5604fd3eaf98e77ecc552c to allow the app to work.

### CODE REVIEW

**Comment by WilliamDormer** [comment]
How can I verify that this is working? I switch to the correct branch, but when I run the app it goes straight to the card swiping page? Shouldn't it start with the login page? Also is there some way to determine if it is working or not?

**Comment by ethanblake4** [comment]
@WilliamDormer oh right. well clearing the app data would do it, but I also just pushed a temporary commit that should fix that for now

**Comment by WilliamDormer** [comment]
I still cannot verify how it works. AuthResult does not seem to have a way to get strings representing the different parts of its result, so I cannot print a debug statement.

**Comment by ethanblake4** [comment]
@WilliamDormer you mean AuthResponse? It should have fields for token, UUID and user_exists.

If you mean AuthRequest, it's a union so you have to use `when`

**Comment by WilliamDormer** [comment]
Hmm, I don't know how to access those fields, but I trust you.

**Pull request merged**
